services:
  backend:
    build: ./be
    image: backend
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/washing-machines-db
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - ./be:/src
    networks:
      - backend-db-network
      - frontend-backend-network

  frontend:
    build: ./fe
    image: frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend
    volumes:
      - ./fe:/src
    networks:
      - frontend-backend-network

  mongodb:
    image: mongo:6-jammy
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=VRuAd2Nvmp4ELHh5
      - MONGO_INITDB_DATABASE=washing-machines-db
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - backend-db-network

volumes:
  dbdata6:


networks:
  backend-db-network:
    driver: bridge
  frontend-backend-network:
    driver: bridge
